/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers_.$customerId'
import { Route as CustomersImportRouteImport } from './routes/customers_.import'
import { Route as CustomersNewRouteImport } from './routes/customers_.new'
import { Route as SettingsDatabaseRouteImport } from './routes/settings.database'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers_/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersImportRoute = CustomersImportRouteImport.update({
  id: '/customers_/import',
  path: '/customers/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers_/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDatabaseRoute = SettingsDatabaseRouteImport.update({
  id: '/settings/database',
  path: '/settings/database',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers/import': typeof CustomersImportRoute
  '/customers/new': typeof CustomersNewRoute
  '/settings/database': typeof SettingsDatabaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers/import': typeof CustomersImportRoute
  '/customers/new': typeof CustomersNewRoute
  '/settings/database': typeof SettingsDatabaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/customers_/$customerId': typeof CustomersCustomerIdRoute
  '/customers_/import': typeof CustomersImportRoute
  '/customers_/new': typeof CustomersNewRoute
  '/settings/database': typeof SettingsDatabaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/customers/$customerId'
    | '/customers/import'
    | '/customers/new'
    | '/settings/database'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/customers/$customerId'
    | '/customers/import'
    | '/customers/new'
    | '/settings/database'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/customers_/$customerId'
    | '/customers_/import'
    | '/customers_/new'
    | '/settings/database'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  CustomersImportRoute: typeof CustomersImportRoute
  CustomersNewRoute: typeof CustomersNewRoute
  SettingsDatabaseRoute: typeof SettingsDatabaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers_/$customerId': {
      id: '/customers_/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers_/import': {
      id: '/customers_/import'
      path: '/customers/import'
      fullPath: '/customers/import'
      preLoaderRoute: typeof CustomersImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers_/new': {
      id: '/customers_/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/database': {
      id: '/settings/database'
      path: '/settings/database'
      fullPath: '/settings/database'
      preLoaderRoute: typeof SettingsDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  CustomersImportRoute: CustomersImportRoute,
  CustomersNewRoute: CustomersNewRoute,
  SettingsDatabaseRoute: SettingsDatabaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
