[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [{ id = "trailing-whitespace" }]

[[repos]]
repo = "local"
hooks = [
  { id = "js-lint", name = "js lint", language = "system", entry = "nub run lint", pass_filenames = false, files = { glob = [
    "src/**/*.tsx",
    "src/**/*.ts",
  ] } },
  { id = "format", name = "format", language = "system", entry = "nub run fmt", files = { glob = [
    "src/**/*.tsx",
    "src/**/*.ts",
    "./**/*.json",
    "./**/*.md",
  ] } },
]
